services:
  gophkeeper:
    build:
      context: .
      dockerfile: Dockerfile
    image: gophkeeper-app
    container_name: gophkeeper-app
    restart: always
    environment:
      - MASTER_DATABASE_URI=postgres://postgres:postgres@gophkeeper-postgres:5432/yap-gophkeeper?sslmode=disable
      - GRPC_SERVER=:3300
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_TIMEOUT_SEC=2
      - TOKEN_NAME=token
      - TOKEN_EXP_HOURS=24
      - TOKEN_SECRET=secret
      - SERVER_CERT_FILE=/internal/tlsconfig/cert/server/server.crt
      - SERVER_KEY_FILE=/internal/tlsconfig/cert/server/server.key
      - SERVER_CA_FILE=/internal/tlsconfig/cert/server/ca.crt
    ports:
      - "3300:3300"
    depends_on:
      - redis
      - pg-1

  redis:
    image: redis:7-alpine3.20
    container_name: gophkeeper-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - REDIS_DATABASES=0
    volumes:
      - redis_data:/data

  pg-1:
    container_name: gophkeeper-master-db
    image: docker.io/bitnami/postgresql-repmgr:16.3.0
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5436:5432"
    volumes:
      - gophkeeper_master_db:/bitnami/postgresql
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=gophkeeper
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-1
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-1,pg-2:5432
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_CONNECT_TIMEOUT=1
      - REPMGR_RECONNECT_ATTEMPTS=2
      - REPMGR_RECONNECT_INTERVAL=1
      - REPMGR_MASTER_RESPONSE_TIMEOUT=5
    restart: unless-stopped

  pg-2:
    container_name: gophkeeper-slave-db
    image: docker.io/bitnami/postgresql-repmgr:16.3.0
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5437:5432"
    volumes:
      - gophkeeper_slave_db:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=gophkeeper
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-1
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-1,pg-2:5432
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_CONNECT_TIMEOUT=1
      - REPMGR_RECONNECT_ATTEMPTS=2
      - REPMGR_RECONNECT_INTERVAL=1
      - REPMGR_MASTER_RESPONSE_TIMEOUT=5
    restart: unless-stopped

volumes:
  gophkeeper_master_db:
  gophkeeper_slave_db:
  pg_data:
  redis_data: